version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./DockerSol.sln && dotnet publish ./DockerSol.sln -c Release -o ./obj/Docker/publish"
