version: '3.4'

services:
  servicebuslistener:
    image: ${DOCKER_REGISTRY}/servicebuslistener
    build:
      args:
        source: .
      context: .
      dockerfile: ServiceBusListener/Dockerfile